spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/majpro
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8044

product-service:
  messages:
    categoryAdded: Category Added Successfully
    categoryAddErr: Failed to Add Category
    categoryUpdate: Category Updated Successfully
    categoryUpdateErr: Failed to Update Category
    categoryFetch: Category Fetched All Successfully
    categoryFetchErr: Failed to Fetch All Categories
    categoryDelete: Category Deleted Successfully
    categoryDeleteErr: Failed to Delete Category
    categorySelect: Category Retrieved Successfully
    categorySelectErr: Category Failed to Retrieve
    productFetch: All Products Fetched Successfully
    productFetchErr: Failed to Fetch All Products
    productAdd: Product Added Successfully
    productAddErr: Failed to Add Product
    productUpdate: Product Updated Successfully
    productUpdateErr: Failed to Update Product
    productSelect: Selected Product Fetched Successfully
    productSelectErr: Failed to Fetch Selected Product
    deleteProduct: Product Deleted Successfully
    deleteProductErr: Failed to Delete Product
    stockUpdate: Stocks Updated Successfully
    stockUpdateErr: Failed to Update Stocks

