spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/majpro
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8044

product-service:
  messages:
    categoryAdded: Category Added SucessFully
    categoryAddErr: Failed to Add Category
    categoryUpdate: Category Updated SucessFully
    categoryUpdateErr: Failed to Update Category
    categoryFetch: Category Fetched All SucessFully
    categoryFetchErr: Failed to Fetch All Category
    categoryDelete: Category deleted SucessFully
    categoryDeleteErr: Failed to Delete Category
    categorySelect: Category Retrieved SucessFully
    categorySelectErr: Category Failed to Retrieve
    ProductFetch: All Products Fetched Successfully
    ProductFetchErr: Failed to Fetch All Products
    ProductAdd: Product Added Successfully
    ProductAddErr: Failed to Add The Product
    ProductUpdate: Product Updated Successfully
    ProductUpdateErr: Failed to Update the Product
    ProductSelect: Selected Product Fetched Successfully
    ProductSelectErr: Failed to Fetch Selected Product
    DeleteProduct: Product Deleted Successfully
    DeleteProductErr: Failed to Delete the Product
    StockUpdate: Stocks Updated Successfully
    StockUpdateErr: Failed to Update Stocks

